feat(ui): fancy Husky setup

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,7 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+echo "✨ Running pre-commit hooks..."
 npx prettier --write .
-npm run lint -- --fix
+npm run lint -- --fixnpx lint-staged || { echo "❌ Lint failed! Fix it before commit." ; exit 1; }
+echo "✅ All good, committing..."npx lint-staged
